config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  devise_for :admins
  resources :orders, only: [:create]
  get '/restaurants/:id', to: 'restaurants#show', as: 'restaurant'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # relationships
  has_and_belongs_to_many :restaurants,
    join_table: "restaurant_managers",
    association_foreign_key: "restaurant_id",
    foreign_key: 'manager_id'
  has_one :kitchen_operator, foreign_key: 'operator_id'
  has_one :kitchen, through: :kitchen_operator

  # validations
  enum role: [:manager, :operator, :siteadmin]
  validates :role, inclusion: { in: roles.keys }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  attr_accessor :total_price
  after_save :update_total_price
  after_initialize :update_total_price

  # relationships
  belongs_to :restaurant
  belongs_to :customer
  has_many :orders, dependent: :delete_all

  # validations
  enum state: [:open, :closed, :archived]
  validates :state, inclusion: { in: states.keys }

  def update_total_price
    self.total_price = 0
    self.orders.each { |order| self.total_price += order.sub_total_price } unless self.orders.nil?
  end

end

app/models/category.rb
class Category < ApplicationRecord
  # relationships
  belongs_to :restaurant
  has_and_belongs_to_many :products, join_table: "product_categories"

  # validations
  validates :title, presence: true, uniqueness: {
    case_sensitive: false,
    scope: :restaurant_id
  }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # relationships
  has_many :carts

  # validations

end

app/models/kitchen.rb
class Kitchen < ApplicationRecord
  # relationships
  belongs_to :restaurant
  has_many :products
  has_many :orders
  has_one :kitchen_operator
  has_one :operator, class_name: "Admin", through: :kitchen_operator

  # validations
  validates :name, presence: true, uniqueness: {
    case_sensitive: false,
    scope: :restaurant_id
  }
end

app/models/kitchen_operator.rb
class KitchenOperator < ApplicationRecord
  # relationships
  belongs_to :kitchen
  belongs_to :operator, class_name: "Admin"

  # validations
  validate :only_operator_allowed

  private
    def only_operator_allowed
      unless self.operator.operator?
        errors.add(:operator, "does not have a Operator role")
      end
    end
end

app/models/order.rb
class Order < ApplicationRecord
  attr_accessor :sub_total_price
  after_save :update_sub_total_price
  after_initialize :update_sub_total_price

  # relationships
  belongs_to :cart
  belongs_to :kitchen
  belongs_to :product
  has_one :customer, through: :cart

  # validations
  enum state: [:selected, :sent_to_kitchen, :prepared, :served]
  validates :state, inclusion: { in: states.keys }

  def update_sub_total_price
    if self.product.nil?
      self.sub_total_price = 0
    else
      self.sub_total_price = self.quantity * self.product.price
    end
  end

end

app/models/product.rb
class Product < ApplicationRecord
  # relationships
  belongs_to :kitchen
  has_many :product_variants
  has_and_belongs_to_many :categories, join_table: "product_categories"
  has_one_attached :image

  # validations
  validates :title, presence: true, uniqueness: {
    case_sensitive: false,
    scope: :kitchen_id
  }
  enum available: [:in_stock, :out_of_stock]
  validates :available, inclusion: { in: availables.keys }
  validates_numericality_of :price, greater_than: 0.0
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  # relationships
  belongs_to :product
  belongs_to :category

  # validations
  
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
  # relationships
  belongs_to :product
  has_one_attached :image

  # validations
  validates :title, presence: true, uniqueness: {
    case_sensitive: false,
    scope: :product_id
  }
  enum available: [:in_stock, :out_of_stock]
  validates :available, inclusion: { in: availables.keys }
  validates_numericality_of :add_on_price, greater_than_or_equal_to: 0.0
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  # relationships
  has_and_belongs_to_many :managers,
    join_table: "restaurant_managers",
    association_foreign_key: "manager_id",
    class_name: "Admin",
    foreign_key: 'restaurant_id'
  has_many :kitchens
  has_many :carts
  has_many :categories
  has_many :products, through: :kitchens

  # validations
  validates :brand, presence: true, uniqueness: {
    case_sensitive: false
  }
  validates :branch, presence: true, uniqueness: {
    case_sensitive: false,
    scope: :brand
  }

end

app/models/restaurant_manager.rb
class RestaurantManager < ApplicationRecord
  # relationships
  belongs_to :restaurant
  belongs_to :manager, class_name: "Admin"

  # validations
  validate :only_manager_allowed

  private
    def only_manager_allowed
      unless self.manager.manager?
        errors.add(:manager, "does not have a Manager role")
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    # get the parent cart
    cart = Cart.find(order_params[:cart_id])
    if !cart.nil? && cart.open?
      # find if the product has already been added
      dup = find_duplicate(cart, order_params[:product_id])
      if dup.nil?
        # create a new order item if none exists
        @order = Order.selected.create!(order_params)
      else
        # just increase the quantity of existing order
        inc = order_params[:quantity].to_i
        if dup.quantity + inc <= 0
          dup.destroy!
        else
          dup.update!( quantity: dup.quantity+inc )
        end
      end
    end

    # redirect back to the restaurants page
    redirect_to cart.restaurant
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.permit(:quantity, :state, :kitchen_id, :product_id, :cart_id)
    end

    # find an order with the same product id
    def find_duplicate(cart, product_id)
      cart.orders.find_by_product_id(product_id)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_restaurant, only: [:show]

  # GET /restaurants/1
  def show
    # get the current active cart or a new one for the customer
    @cart = validate_active_cart

    # return the categories (and the corresponding products)
    @categories = @restaurant.categories
  end

  protected
    def active_cart
      cart = current_customer.carts.open.first ||
        current_customer.carts.open.create!(restaurant:@restaurant)
      cart
    end

    helper_method :active_cart

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def validate_active_cart
      # get the last used cart for current customer
      cart = active_cart

      # check if the active cart has expired
      if Time.now > cart.updated_at + 15.minutes
        # cart has expired, so destroy it
        cart.destroy!

        # create a new cart
        cart = current_customer.carts.open.create!(restaurant:@restaurant)
      end

      cart
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=  "#{yield(:title)} | " if content_for?(:title) %>GreenBowl</title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "GreenBowl" %>">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div id="user_nav">
      <% if customer_signed_in? %>
          Signed in as <%= current_customer.email %>. This cannot be cheese?
          <%= link_to "Sign out", destroy_customer_session_path, :method => :delete %>
      <% else %>
          <%= link_to 'Register', new_customer_registration_path %> or <%= link_to 'Sign in', new_customer_session_path %>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/restaurants/show.html.erb
<% content_for :title, @restaurant.brand %>

<h1><div id="brand"><%= @restaurant.brand %></div></h1>
<h3><div id="branch"><%= @restaurant.branch %></div></h3>

<div>
  <% unless @cart.nil? %>
    <% @cart.orders.each do |order| %>
      <% product = order.product %>
      <div>
        <%= product.title %>
        $ <%= product.price %> x <%= order.quantity %> = <strong>$ <%= order.sub_total_price %></strong>
        <% if @cart.open? && product.available? %>
          <%= form_tag url_for(:controller => 'orders', :action => 'create'), :method => 'post' do %>
            <%= hidden_field_tag :product_id, product.id %>
            <%= hidden_field_tag :kitchen_id, product.kitchen_id %>
            <%= hidden_field_tag :cart_id, @cart.id %>
            <%= hidden_field_tag :quantity, 1 %>
            <%= submit_tag "+" %>
          <% end %>
          <%= form_tag url_for(:controller => 'orders', :action => 'create'), :method => 'post' do %>
            <%= hidden_field_tag :product_id, product.id %>
            <%= hidden_field_tag :kitchen_id, product.kitchen_id %>
            <%= hidden_field_tag :cart_id, @cart.id %>
            <%= hidden_field_tag :quantity, -1 %>
            <% if order.quantity == 1  %>
              <%= submit_tag "-", data: {confirm: "Are you sure?"} %>
            <% else %>
              <%= submit_tag "-" %>
            <% end %>
          <% end %>
        <% end  %>
      </div>
    <% end %>
    <div>Total: <strong>$<%= @cart.total_price %></strong></div>
  <% end %>
</div>


<div>
  <% unless @categories.nil? %>
    <% @categories.each do |cat| %>
      <% products = cat.products.in_stock.all %>
      <% if products.length > 0 %>
        <h3><%= cat.title %></h3>
        <% products.each do |product| %>
          <div>
            <%= product.title %>
            <strong>$ <%= product.price %></strong>
            <%= form_tag url_for(:controller => 'orders', :action => 'create'), :method => 'post' do %>
              <%= hidden_field_tag :product_id, product.id %>
              <%= hidden_field_tag :kitchen_id, product.kitchen_id %>
              <%= hidden_field_tag :cart_id, @cart.id %>
              <%= hidden_field_tag :quantity, 1 %>
              <%= submit_tag "Add to Cart" if @cart.open? && product.available? %>
            <% end %>
          </div>
          <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>